@startuml

class StudentReport {
    +main(args : String[]) : void
}

class "java.sql.Connection" as Connection
class "java.sql.Statement" as Statement
class "java.sql.ResultSet" as ResultSet

StudentReport ..> Connection : <<uses>>
Connection --> Statement
Statement --> ResultSet : <<returns>>

@enduml
